import datetime

from flask.cli import AppGroup

from applications.extensions import db
from applications.models import User, Role, Dept, Power

admin_cli = AppGroup("admin")

now_time = datetime.datetime.now()
userdata = [
    User(
        id=1,
        username='admin',
        password_hash='pbkdf2:sha256:150000$raM7mDSr$58fe069c3eac01531fc8af85e6fc200655dd2588090530084d182e6ec9d52c85',
        create_at=now_time,
        enable=1,
        realname='超级管理',
        remark='要是不能把握时机，就要终身蹭蹬，一事无成！',
        avatar='/static/system/admin/images/avatar.jpg',
        dept_id=1,
    ),
    User(
        id=2,
        username='test',
        password_hash='pbkdf2:sha256:150000$cRS8bYNh$adb57e64d929863cf159f924f74d0634f1fecc46dba749f1bfaca03da6d2e3ac',
        create_at=now_time,
        enable=1,
        realname='测试',
        remark='要是不能把握时机，就要终身蹭蹬，一事无成！',
        avatar='/static/system/admin/images/avatar.jpg',
        dept_id=1,
    ),
]
roledata = [
    Role(
        id=1,
        code='admin',
        name='管理员',
        enable=1,
        details='管理员',
        sort=1,
        create_time=now_time,
    ),
    Role(
        id=2,
        code='common',
        name='普通用户',
        enable=1,
        details='只有中台权限',
        sort=2,
        create_time=now_time,
    )
]
deptdata = [
    Dept(
        id=1,
        parent_id=0,
        dept_name='RUAN',
        sort=1,
        leader='admin',
        phone='13504285070',
        email='3838311763@qq.com',
        status=1,
        remark='这是RUAN总部',
        create_at=now_time
    ),
    Dept(
        id=4,
        parent_id=1,
        dept_name='RUAN（浑南）',
        sort=2,
        leader='admin',
        phone='13504285070',
        email='3838311763@qq.com',
        status=1,
        remark='这是RUAN（浑南）',
        create_at=now_time

    ),
    Dept(
        id=5,
        parent_id=1,
        dept_name='RUAN（南湖）',
        sort=4,
        leader='admin',
        phone='13504285070',
        email='3838311763@qq.com',
        status=1,
        remark='这是RUAN（南湖）',
        create_at=now_time

    ),
    Dept(
        id=7,
        parent_id=4,
        dept_name='RUAN（美国）',
        sort=5,
        leader='admin',
        phone='13504285070',
        email='3838311763@qq.com',
        status=1,
        remark='这是RUAN（美国）',
        create_at=now_time

    ),
    Dept(
        id=8,
        parent_id=5,
        dept_name='RUAN（日本）',
        sort=5,
        leader='admin',
        phone='13504285070',
        email='3838311763@qq.com',
        status=1,
        remark='这是RUAN（日本）',
        create_at=now_time

    )
]

powerdata = [Power(id=id, name=name, type=type, code=code, url=url, open_type=open_type, parent_id=parent_id, icon=icon,
                   sort=sort, create_time=create_time, update_time=update_time, enable=enable) for
             id, name, type, code, url, open_type, parent_id, icon, sort, create_time, update_time, enable in [(1,
                                                                                                                '系统管理',
                                                                                                                '0', '',
                                                                                                                None,
                                                                                                                None, 0,
                                                                                                                'layui-icon layui-icon-set-fill',
                                                                                                                1,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (3,
                                                                                                                '用户管理',
                                                                                                                '1',
                                                                                                                'system:user:main',
                                                                                                                '/system/user/',
                                                                                                                '_iframe',
                                                                                                                1,
                                                                                                                'layui-icon layui-icon layui-icon layui-icon layui-icon-rate',
                                                                                                                1,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (4,
                                                                                                                '权限管理',
                                                                                                                '1',
                                                                                                                'system:power:main',
                                                                                                                '/system/power/',
                                                                                                                '_iframe',
                                                                                                                1, None,
                                                                                                                2,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (9,
                                                                                                                '角色管理',
                                                                                                                '1',
                                                                                                                'system:role:main',
                                                                                                                '/system/role',
                                                                                                                '_iframe',
                                                                                                                1,
                                                                                                                'layui-icon layui-icon-username',
                                                                                                                2,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (12,
                                                                                                                '系统监控',
                                                                                                                '1',
                                                                                                                'system:monitor:main',
                                                                                                                '/system/monitor',
                                                                                                                '_iframe',
                                                                                                                1,
                                                                                                                'layui-icon layui-icon-vercode',
                                                                                                                5,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                0),
                                                                                                               (13,
                                                                                                                '日志管理',
                                                                                                                '1',
                                                                                                                'system:log:main',
                                                                                                                '/system/log',
                                                                                                                '_iframe',
                                                                                                                1,
                                                                                                                'layui-icon layui-icon-read',
                                                                                                                4,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (17,
                                                                                                                '文件管理',
                                                                                                                '0', '',
                                                                                                                '', '',
                                                                                                                0,
                                                                                                                'layui-icon layui-icon-camera',
                                                                                                                2,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (18,
                                                                                                                '图片上传',
                                                                                                                '1',
                                                                                                                'system:file:main',
                                                                                                                '/system/file',
                                                                                                                '_iframe',
                                                                                                                17,
                                                                                                                'layui-icon layui-icon-camera',
                                                                                                                5,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (21,
                                                                                                                '权限增加',
                                                                                                                '2',
                                                                                                                'system:power:add',
                                                                                                                '', '',
                                                                                                                4,
                                                                                                                'layui-icon layui-icon-add-circle',
                                                                                                                1,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (22,
                                                                                                                '用户增加',
                                                                                                                '2',
                                                                                                                'system:user:add',
                                                                                                                '', '',
                                                                                                                3,
                                                                                                                'layui-icon layui-icon-add-circle',
                                                                                                                1,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (23,
                                                                                                                '用户编辑',
                                                                                                                '2',
                                                                                                                'system:user:edit',
                                                                                                                '', '',
                                                                                                                3,
                                                                                                                'layui-icon layui-icon-rate',
                                                                                                                2,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (24,
                                                                                                                '用户删除',
                                                                                                                '2',
                                                                                                                'system:user:remove',
                                                                                                                '', '',
                                                                                                                3, '',
                                                                                                                3,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (25,
                                                                                                                '权限编辑',
                                                                                                                '2',
                                                                                                                'system:power:edit',
                                                                                                                '', '',
                                                                                                                4, '',
                                                                                                                2,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (26,
                                                                                                                '用户删除',
                                                                                                                '2',
                                                                                                                'system:power:remove',
                                                                                                                '', '',
                                                                                                                4, '',
                                                                                                                3,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (27,
                                                                                                                '用户增加',
                                                                                                                '2',
                                                                                                                'system:role:add',
                                                                                                                '', '',
                                                                                                                9, '',
                                                                                                                1,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (28,
                                                                                                                '角色编辑',
                                                                                                                '2',
                                                                                                                'system:role:edit',
                                                                                                                '', '',
                                                                                                                9, '',
                                                                                                                2,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (29,
                                                                                                                '角色删除',
                                                                                                                '2',
                                                                                                                'system:role:remove',
                                                                                                                '', '',
                                                                                                                9, '',
                                                                                                                3,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (30,
                                                                                                                '角色授权',
                                                                                                                '2',
                                                                                                                'system:role:power',
                                                                                                                '', '',
                                                                                                                9, '',
                                                                                                                4,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (31,
                                                                                                                '图片增加',
                                                                                                                '2',
                                                                                                                'system:file:add',
                                                                                                                '', '',
                                                                                                                18, '',
                                                                                                                1,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (32,
                                                                                                                '图片删除',
                                                                                                                '2',
                                                                                                                'system:file:delete',
                                                                                                                '', '',
                                                                                                                18, '',
                                                                                                                2,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (44,
                                                                                                                '数据字典',
                                                                                                                '1',
                                                                                                                'system:dict:main',
                                                                                                                '/system/dict',
                                                                                                                '_iframe',
                                                                                                                1,
                                                                                                                'layui-icon layui-icon-console',
                                                                                                                6,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                0),
                                                                                                               (45,
                                                                                                                '字典增加',
                                                                                                                '2',
                                                                                                                'system:dict:add',
                                                                                                                '', '',
                                                                                                                44, '',
                                                                                                                1,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (46,
                                                                                                                '字典修改',
                                                                                                                '2',
                                                                                                                'system:dict:edit',
                                                                                                                '', '',
                                                                                                                44, '',
                                                                                                                2,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (47,
                                                                                                                '字典删除',
                                                                                                                '2',
                                                                                                                'system:dict:remove',
                                                                                                                '', '',
                                                                                                                44, '',
                                                                                                                3,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (49,
                                                                                                                '部门增加',
                                                                                                                '2',
                                                                                                                'system:dept:add',
                                                                                                                '', '',
                                                                                                                48, '',
                                                                                                                1,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (50,
                                                                                                                '部门编辑',
                                                                                                                '2',
                                                                                                                'system:dept:edit',
                                                                                                                '', '',
                                                                                                                48, '',
                                                                                                                2,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (51,
                                                                                                                '部门删除',
                                                                                                                '2',
                                                                                                                'system:dept:remove',
                                                                                                                '', '',
                                                                                                                48, '',
                                                                                                                3,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (57,
                                                                                                                '邮件管理',
                                                                                                                '1',
                                                                                                                'system:mail:main',
                                                                                                                '/system/mail',
                                                                                                                '_iframe',
                                                                                                                1,
                                                                                                                'layui-icon ',
                                                                                                                7,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (58,
                                                                                                                '邮件发送',
                                                                                                                '2',
                                                                                                                'system:mail:add',
                                                                                                                '', '',
                                                                                                                57,
                                                                                                                'layui-icon layui-icon-ok-circle',
                                                                                                                1,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (59,
                                                                                                                '邮件删除',
                                                                                                                '2',
                                                                                                                'system:mail:remove',
                                                                                                                '', '',
                                                                                                                57, '',
                                                                                                                2,
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                '2024-12-27 15:41:08',
                                                                                                                1),
                                                                                                               (60,
                                                                                                                '博客管理',
                                                                                                                '0',
                                                                                                                None,
                                                                                                                None,
                                                                                                                None, 0,
                                                                                                                'layui-icon layui-icon-spread-left',
                                                                                                                3,
                                                                                                                '2024-12-27 16:19:50',
                                                                                                                '2024-12-27 16:20:19',
                                                                                                                1),
                                                                                                               (61,
                                                                                                                '博客文章管理',
                                                                                                                '1',
                                                                                                                'system:post:main',
                                                                                                                '/system/post',
                                                                                                                '_iframe',
                                                                                                                60,
                                                                                                                'layui-icon ',
                                                                                                                3,
                                                                                                                '2024-12-27 16:21:22',
                                                                                                                '2024-12-27 16:21:22',
                                                                                                                1),
                                                                                                               (62,
                                                                                                                '博客评论管理',
                                                                                                                '1',
                                                                                                                'system:comment:main',
                                                                                                                '/system/comment',
                                                                                                                '_iframe',
                                                                                                                60,
                                                                                                                'layui-icon ',
                                                                                                                3,
                                                                                                                '2024-12-27 16:22:05',
                                                                                                                '2024-12-27 16:22:05',
                                                                                                                1),
                                                                                                               (63,
                                                                                                                '最新情报管理',
                                                                                                                '1',
                                                                                                                'system:news:main',
                                                                                                                '/system/news',
                                                                                                                '_iframe',
                                                                                                                66,
                                                                                                                'layui-icon layui-icon layui-icon-menu-fill',
                                                                                                                4,
                                                                                                                '2024-12-27 17:58:46',
                                                                                                                '2024-12-28 00:51:00',
                                                                                                                1),
                                                                                                               (64,
                                                                                                                '系列管理',
                                                                                                                '0',
                                                                                                                None,
                                                                                                                None,
                                                                                                                None, 0,
                                                                                                                'layui-icon layui-icon-template-1',
                                                                                                                5,
                                                                                                                '2024-12-27 17:59:15',
                                                                                                                '2024-12-27 17:59:15',
                                                                                                                1),
                                                                                                               (65,
                                                                                                                '篇章故事管理',
                                                                                                                '0',
                                                                                                                None,
                                                                                                                None,
                                                                                                                None, 0,
                                                                                                                'layui-icon layui-icon-senior',
                                                                                                                6,
                                                                                                                '2024-12-27 17:59:49',
                                                                                                                '2024-12-28 01:01:55',
                                                                                                                1),
                                                                                                               (66,
                                                                                                                '最新情报管理',
                                                                                                                '0',
                                                                                                                None,
                                                                                                                None,
                                                                                                                None, 0,
                                                                                                                'layui-icon layui-icon-website',
                                                                                                                4,
                                                                                                                '2024-12-28 00:51:43',
                                                                                                                '2024-12-28 01:02:13',
                                                                                                                1),
                                                                                                               (67,
                                                                                                                '系列管理',
                                                                                                                '1',
                                                                                                                'system:series:main',
                                                                                                                '/system/series',
                                                                                                                '_iframe',
                                                                                                                64,
                                                                                                                'layui-icon layui-icon-template-1',
                                                                                                                5,
                                                                                                                '2024-12-27 17:59:15',
                                                                                                                '2024-12-27 17:59:15',
                                                                                                                1),
                                                                                                               (68,
                                                                                                                '篇章故事管理',
                                                                                                                '1',
                                                                                                                'system:topic:main',
                                                                                                                '/system/topic',
                                                                                                                '_iframe',
                                                                                                                65,
                                                                                                                'layui-icon ',
                                                                                                                5,
                                                                                                                '2024-12-27 17:59:49',
                                                                                                                '2024-12-27 17:59:49',
                                                                                                                1),
                                                                                                               (69,
                                                                                                                '我的博客',
                                                                                                                '0',
                                                                                                                'user:blog:main',
                                                                                                                None,
                                                                                                                None, 0,
                                                                                                                'layui-icon layui-icon layui-icon-spread-left',
                                                                                                                7,
                                                                                                                '2024-12-28 00:56:58',
                                                                                                                '2024-12-29 13:23:50',
                                                                                                                1),
                                                                                                               (70,
                                                                                                                '我的评论',
                                                                                                                '0',
                                                                                                                'user:comment:main',
                                                                                                                None,
                                                                                                                None, 0,
                                                                                                                'layui-icon layui-icon layui-icon-dialogue',
                                                                                                                8,
                                                                                                                '2024-12-28 00:57:44',
                                                                                                                '2024-12-29 13:23:55',
                                                                                                                1),
                                                                                                               (71,
                                                                                                                '用户资料',
                                                                                                                '0',
                                                                                                                'user:info:main',
                                                                                                                None,
                                                                                                                None, 0,
                                                                                                                'layui-icon layui-icon layui-icon-username',
                                                                                                                9,
                                                                                                                '2024-12-28 01:01:24',
                                                                                                                '2024-12-29 13:23:59',
                                                                                                                1),
                                                                                                               (72,
                                                                                                                '博客管理',
                                                                                                                '1',
                                                                                                                'user:blog:list',
                                                                                                                '/blog/home/post',
                                                                                                                '_iframe',
                                                                                                                69,
                                                                                                                'layui-icon layui-icon-spread-left',
                                                                                                                1,
                                                                                                                '2024-12-29 13:19:14',
                                                                                                                '2024-12-29 13:19:14',
                                                                                                                1),
                                                                                                               (73,
                                                                                                                '新建博客',
                                                                                                                '1',
                                                                                                                'user:blog:add',
                                                                                                                '/blog/home/post/add',
                                                                                                                '_iframe',
                                                                                                                69,
                                                                                                                'layui-icon layui-icon-file-b',
                                                                                                                2,
                                                                                                                '2024-12-29 13:20:09',
                                                                                                                '2024-12-29 13:20:09',
                                                                                                                1),
                                                                                                               (74,
                                                                                                                '评论管理',
                                                                                                                '1',
                                                                                                                'user:comment:edit',
                                                                                                                '/blog/home/comment',
                                                                                                                '_iframe',
                                                                                                                70,
                                                                                                                'layui-icon layui-icon-dialogue',
                                                                                                                3,
                                                                                                                '2024-12-29 13:20:57',
                                                                                                                '2024-12-29 13:20:57',
                                                                                                                1),
                                                                                                               (75,
                                                                                                                '基础信息',
                                                                                                                '1',
                                                                                                                'user:info:edit',
                                                                                                                '/system/user/center',
                                                                                                                '_iframe',
                                                                                                                71,
                                                                                                                'layui-icon ',
                                                                                                                1,
                                                                                                                '2024-12-29 13:21:32',
                                                                                                                '2024-12-29 13:21:32',
                                                                                                                1),
                                                                                                               (76,
                                                                                                                '漫画管理',
                                                                                                                '1',
                                                                                                                'system:gallery:main',
                                                                                                                '/system/gallery',
                                                                                                                '_iframe',
                                                                                                                17,
                                                                                                                'layui-icon ',
                                                                                                                2,
                                                                                                                '2024-12-31 02:00:39',
                                                                                                                '2024-12-31 02:00:39',
                                                                                                                1)]]


def add_user_role():
    admin_role = Role.query.filter_by(id=1).first()
    admin_user = User.query.filter_by(id=1).first()
    admin_user.role.append(admin_role)
    test_role = Role.query.filter_by(id=2).first()
    test_user = User.query.filter_by(id=2).first()
    test_user.role.append(test_role)
    db.session.commit()


def add_role_power():
    common_powers = Power.query.filter(Power.id.in_([12, 13, 44, 3, 18, 4, 9, 70, 69, 71, 74, 72, 75, 73, 76])).all()
    common_user = Role.query.filter_by(id=2).first()
    for i in common_powers:
        common_user.power.append(i)
    db.session.commit()
    admin_powers = Power.query.all()
    admin_user = Role.query.filter_by(id=1).first()
    for i in admin_powers:
        admin_user.power.append(i)
    db.session.commit()


@admin_cli.command("init")
def init_db():
    db.session.add_all(userdata)
    print("加载系统必须用户数据")
    db.session.add_all(roledata)
    print("加载系统必须角色数据")
    db.session.add_all(deptdata)
    print("加载系统必须部门数据")
    db.session.add_all(powerdata)
    print("加载系统必须权限数据")
    db.session.commit()
    print("基础数据存入")
    add_user_role()
    print("用户角色数据存入")
    add_role_power()
    print("角色权限数据存入")
    print("数据初始化完成,请使用run脚本运行")
