"""Add original_work and anime columns to blog_topic

Revision ID: 33840190cab3
Revises: 
Create Date: 2025-12-09 11:33:34.410839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33840190cab3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_work', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('anime', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_topic', schema=None) as batch_op:
        batch_op.drop_column('anime')
        batch_op.drop_column('original_work')

    # ### end Alembic commands ###
