"""Add user_favorite table with unique constraint

Revision ID: bffcae59eefd
Revises: d8f5940f2250
Create Date: 2025-12-18 15:01:58.676743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffcae59eefd'
down_revision = 'd8f5940f2250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_favorite_relation', ['user_id', 'post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite', schema=None) as batch_op:
        batch_op.drop_constraint('unique_favorite_relation', type_='unique')

    # ### end Alembic commands ###
