"""Add UserLike model

Revision ID: c55b05d60db6
Revises: 8cfac7db7656
Create Date: 2025-12-18 14:16:33.446170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c55b05d60db6'
down_revision = '8cfac7db7656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_follow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follow',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='关注关系ID'),
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关注者ID'),
    sa.Column('followed_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='被关注者ID'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='关注时间'),
    sa.ForeignKeyConstraint(['followed_id'], ['admin_user.id'], name='user_follow_ibfk_2'),
    sa.ForeignKeyConstraint(['follower_id'], ['admin_user.id'], name='user_follow_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
