"""Add user_follow and user_favorite tables

Revision ID: d8f5940f2250
Revises: c55b05d60db6
Create Date: 2025-12-18 14:52:43.014431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8f5940f2250'
down_revision = 'c55b05d60db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_like',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='点赞关系ID'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('news_article_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新闻文章ID'),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='博客文章ID'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='点赞时间'),
    sa.ForeignKeyConstraint(['news_article_id'], ['blog_news.id'], name='user_like_ibfk_2'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], name='user_like_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], name='user_like_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
