"""Create user_follow table for user follow relationships

Revision ID: db4fd8f6c198
Revises: bffcae59eefd
Create Date: 2025-12-18 15:11:23.521396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4fd8f6c198'
down_revision = 'bffcae59eefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关注关系ID'),
    sa.Column('follower_id', sa.Integer(), nullable=False, comment='关注者ID'),
    sa.Column('followed_id', sa.Integer(), nullable=False, comment='被关注者ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='关注时间'),
    sa.ForeignKeyConstraint(['followed_id'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='unique_follow_relation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_follow')
    # ### end Alembic commands ###
