"""add user favorite table

Revision ID: ef390b50d480
Revises: 33840190cab3
Create Date: 2025-12-17 20:52:18.293049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef390b50d480'
down_revision = '33840190cab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='收藏关系ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='收藏时间'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_follow')
    with op.batch_alter_table('admin_role_power', schema=None) as batch_op:
        batch_op.drop_constraint('admin_role_power_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('admin_role_power_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_power', ['power_id'], ['id'])
        batch_op.create_foreign_key(None, 'admin_role', ['role_id'], ['id'])

    with op.batch_alter_table('admin_user_role', schema=None) as batch_op:
        batch_op.drop_constraint('admin_user_role_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('admin_user_role_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'admin_user', ['user_id'], ['id'])

    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_constraint('blog_comments_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('blog_comments_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'blog_posts', ['post_id'], ['id'])

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint('blog_posts_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('blog_posts_ibfk_1', 'admin_user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('blog_comments_ibfk_2', 'blog_posts', ['post_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('blog_comments_ibfk_1', 'admin_user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('admin_user_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_user_role_ibfk_1', 'admin_user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('admin_user_role_ibfk_2', 'admin_role', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('admin_role_power', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_role_power_ibfk_1', 'admin_power', ['power_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('admin_role_power_ibfk_2', 'admin_role', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    op.create_table('user_follow',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='关注关系ID'),
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关注者ID'),
    sa.Column('followed_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='被关注者ID'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='关注时间'),
    sa.ForeignKeyConstraint(['followed_id'], ['admin_user.id'], name='user_follow_ibfk_2'),
    sa.ForeignKeyConstraint(['follower_id'], ['admin_user.id'], name='user_follow_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_favorite')
    # ### end Alembic commands ###
